name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      id-token: write
    name: Release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
      - name: Sleep
        run: sleep 30s
        shell: bash
